In [1]:
# NumPy exercises

In [2]:
# Import numpy in the usual way, with the alias np

import numpy as np

In [3]:
# Create a 10-element numpy array of zeros

ten_zeros = np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Create a 10-element numpy array of zeros, then assign the fifth element of the array to 1

ten_zeros = np.zeros(10)
ten_zeros[4] = 1
ten_zeros

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [5]:
# Create a numpy array with values ranging from 10 to 49

np_range = np.arange(10, 50)
np_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# Create a numpy array with values ranging from 10 to 49, then create a copy of that array that reverses the order

np_range = np.arange(10, 50)[::-1]
np_range

<class 'numpy.ndarray'>


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [7]:
# Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(0, 9).reshape((3, 3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# Create a 3x3 matrix with random values

matrix = np.random.uniform(0, 100, 9).reshape((3, 3))
matrix

array([[30.17981235, 20.35770753, 40.44376074],
       [ 0.42813751,  8.63700452, 90.3286335 ],
       [91.95749239, 42.44737934, 87.51248654]])